server:
  port: 8070
my:
  config:
    name: safsadf
    value: 123
    url: test
    rocketStatus: false
    isAccess: true
    isMock: true

spring:
  application:
    name: nacos-provider
  datasource:
    username: root
    url: jdbc:mysql://118.31.251.1:3306/longge?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    password: wang123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    gateway:
#      routes:
#        - id: url-proxy-1
#          uri: https://blog.csdn.net
#          predicates:
#            - Path=/csdn

  context:
    listener:
      classes: org.wys.demo.spring.event.UserEven

management:
  health:
    elasticsearch:
      enabled: false