server:
  port: 8070
my:
  config:
    name: safsadf
    value: 123
    url: test
    rocketStatus: false

spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/longge?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379

  context:
    listener:
      classes: org.wys.demo.spring.event.UserEvent
## NameServer地址
#rocketmq:
#  name-server: 127.0.0.1:9876
## 默认的消息组
#  producer:
#    group: springBootGroup
#  consumer:
#    topic: TestTopic
management:
  health:
    elasticsearch:
      enabled: false