server:
  port: 8078
spring:
  application:
    name: gateway-provider
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/longge?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          enabled: true
  redis:
    host: localhost
    port: 6379

management:
  health:
    elasticsearch:
      enabled: false